export const inspirationPhrases = [
  "Las marcas que conectan son las que escuchan antes de hablar.",
  "No se trata de publicar más. Se trata de impactar mejor.",
  "La creatividad sin ejecución es solo una idea.",
  "Una buena estrategia convierte presencia en preferencia.",
  "Cada contenido debe tener una intención clara.",
  "La consistencia crea confianza antes que la venta.",
  "El mejor branding se siente antes de explicarse.",
  "Vender también es acompañar una decisión.",
  "Un cliente informado decide con más seguridad.",
  "La productividad empieza cuando elegimos prioridades.",
  "El equipo crece cuando la información circula.",
  "Medir no enfría la creatividad, la potencia.",
  "Una campaña fuerte nace de un insight honesto.",
  "Las ideas simples suelen ser las más memorables.",
  "La atención al detalle también comunica marca.",
  "Un proceso claro libera energía creativa.",
  "Lo urgente no siempre es lo importante.",
  "Un buen brief ahorra diez idas y vueltas.",
  "El contenido útil vende sin gritar.",
  "Una marca coherente se reconoce en cada punto de contacto.",
  "El liderazgo ordena, inspira y habilita.",
  "La mejor propuesta habla el idioma del cliente.",
  "Cada reunión debe terminar con próximos pasos.",
  "La colaboración también necesita estructura.",
  "Los datos cuentan una historia; hay que aprender a leerla.",
  "Una comunidad se construye respuesta a respuesta.",
  "La creatividad necesita espacio y fecha de entrega.",
  "Un diseño bello también debe resolver algo.",
  "Las marcas memorables sostienen una voz propia.",
  "Un cliente retenido vale más que una venta apurada.",
  "Las buenas ideas se vuelven mejores en equipo.",
  "El foco es una decisión diaria.",
  "La estrategia evita publicar por inercia.",
  "Una propuesta clara reduce objeciones.",
  "La rentabilidad también es parte del cuidado del proyecto.",
  "Cada entrega es una oportunidad de confianza.",
  "La marca se construye en lo que repetimos bien.",
  "El calendario ordena la creatividad sin apagarla.",
  "Escuchar al cliente también es estrategia.",
  "La ejecución convierte intención en resultado.",
  "El mejor contenido parece simple porque fue pensado.",
  "La claridad vende mejor que el exceso.",
  "Una agencia ordenada crea mejor.",
  "La planificación protege el talento del caos.",
  "La empatía también es una ventaja competitiva.",
  "Un mensaje fuerte empieza con una verdad simple.",
  "La constancia gana más campañas que la inspiración aislada.",
  "El seguimiento oportuno puede salvar una venta.",
  "Los procesos no reemplazan criterio; lo acompañan.",
  "Cada métrica debe responder una pregunta.",
  "La identidad visual es una promesa repetida.",
  "Las ventas crecen cuando la confianza está bien cuidada.",
  "El equipo alineado avanza con menos fricción.",
  "La creatividad florece cuando sabe hacia dónde ir.",
  "Un buen sistema hace visible lo importante.",
  "La experiencia del cliente empieza antes de contratar.",
  "La retención empieza el primer día de servicio.",
  "Un contenido sin objetivo es ruido elegante.",
  "Una marca cercana no improvisa; se prepara.",
  "El orden también puede ser creativo.",
  "La prioridad correcta cambia el día completo.",
  "Vender es mostrar valor con claridad.",
  "Una entrega a tiempo también es comunicación.",
  "Las campañas fuertes tienen estrategia, ritmo y revisión.",
  "El feedback bien gestionado mejora el resultado.",
  "Las ideas brillan más cuando tienen proceso.",
  "Una propuesta ganadora anticipa dudas.",
  "El cliente recuerda cómo lo hiciste sentir.",
  "El contenido debe abrir conversación, no cerrarla.",
  "El margen sano permite sostener calidad.",
  "Los equipos creativos también necesitan tableros claros.",
  "La mejor automatización es la que no deshumaniza.",
  "Una marca fuerte decide qué no decir.",
  "El planner es una brújula, no una jaula.",
  "La calidad se nota en lo que nadie tuvo que corregir.",
  "Cada campaña debería tener una hipótesis.",
  "Lo que no se registra se pierde.",
  "La comunicación interna también impacta al cliente.",
  "Una buena reunión ahorra muchos mensajes.",
  "El trabajo en equipo requiere acuerdos visibles.",
  "La estrategia une creatividad y negocio.",
  "Cada cliente necesita contexto, no plantillas vacías.",
  "Un presupuesto bien armado también educa.",
  "El diseño debe enamorar y orientar.",
  "La productividad no es hacer más, es avanzar mejor.",
  "El liderazgo también es quitar obstáculos.",
  "Una campaña sin seguimiento es una historia incompleta.",
  "El éxito se sostiene con revisión constante.",
  "La marca crece cuando su mensaje madura.",
  "El contenido relevante nace de preguntas mejores.",
  "Una agencia con datos decide con más calma.",
  "La colaboración funciona cuando cada turno está claro.",
  "La mejora continua empieza con mirar el proceso.",
  "La confianza se renueva en cada entrega.",
  "La creatividad profesional también cumple plazos.",
  "Un cliente feliz entiende qué se hizo y por qué.",
  "El mejor dashboard muestra decisiones, no adornos.",
  "Las marcas humanas no suenan automáticas.",
  "La estrategia protege a la creatividad del capricho.",
  "Un buen día empieza con prioridades visibles."
];

export function phraseOfTheDay() {
  const day = Math.floor(Date.now() / 86400000);
  return inspirationPhrases[day % inspirationPhrases.length];
}
